---
title: "Gas Pollution in the US"
author: "Guang Yang"
date: "December 7, 2016"
output: html_document
runtime: shiny
---


##### __Note: If there is a connection problem, please try a couple of times, or email to `guangyang11231987@gmail.com`. Thank you!__

## Introduction

This document originates some cleaned data from the annual pollution data from [EPA Air-Data webpage](https://www.epa.gov/outdoor-air-quality-data), and interactively marks concentrations of `Sulfur Dioxide`, `Carbon Monoxide`, and `Ozone`, by the coordinates of the monitors throughout the US. The [DataGallery.rda](https://github.com/imreyes/datasciencecoursera/blob/master/DevelopingDataProduct/Week2_ProgrammingAssignment/DataGallery.rda) stores the list named `data.gallery` which contains the necessary data chunks for mapping. Codes to generate the list is stored in [GasPollution_DataProcessor.R](https://github.com/imreyes/datasciencecoursera/blob/master/DevelopingDataProduct/Week2_ProgrammingAssignment/GasPollution_DataProcessor.R) file. For more information of [data downloading](https://aqsdr1.epa.gov/aqsweb/aqstmp/airdata/download_files.html) or [data documentation](https://aqsdr1.epa.gov/aqsweb/aqstmp/airdata/FileFormats.html#_annual_summary_files), please follow the links to the EPA websites.

This R Markdown document is made interactive using Shiny. To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

```{r page, echo=FALSE}
library(leaflet)
library(shiny)
if(!file.exists('DataGallery.rda')) {
        Url <- 'https://github.com/imreyes/datasciencecoursera/raw/master/DevelopingDataProduct/Week2_ProgrammingAssignment/DataGallery.rda'
        download.file(Url, destfile = 'Datagallery.rda')
}
load('DataGallery.rda')
        
ui <- shinyUI(fluidPage(
        sidebarLayout(
                sidebarPanel(
                        sliderInput('SliderYear', h3('Slide to select year:'),
                                    1990, 2016, value = 2016),
                        radioButtons('ButtonPol',
                                     label = h3('Pollutant Type:'),
                                     choices = c('Sulfur dioxide' = 1,
                                                 'Carbon monoxide' = 2,
                                                 'Ozone' = 3),
                                     selected = 1)
                        # Use submit button to let user update changes.
                        # submitButton('Submit')
                ),
                mainPanel(
                        leafletOutput('plot')
                )
        )
))

server <- shinyServer(function(input, output, session) {
        output$plot <- renderLeaflet({
                # Get the subset to plot.
                year <- input$SliderYear - 1990
                pol <- as.integer(input$ButtonPol)
                idx <- year * 3 + pol
                plotData <- data.gallery[[idx]]
                # Get the plotting constant to draw properly sized circles.
                med <- median(plotData$x)
                adjust <- 10000 / sqrt(med)
                pal <- colorNumeric(palette = c('lightgreen', 'darkred'),
                                    domain = plotData$x)
                Unit <- ifelse(input$ButtonPol == '1', 'ppb', 'ppm')
                leg <- paste0('Level (', Unit, '):')
                plotData %>%
                        leaflet() %>%
                        addTiles() %>%
                        addCircleMarkers(color = ~ pal(x)) %>%
                        addLegend('bottomright', pal = pal, values = ~plotData$x,
                                  title = leg,
                                  opacity = 0.5)
        })
})

shinyApp(ui, server)
```
